let products = JSON.parse(localStorage.getItem("products")) || [
  {
    id: 1,
    name: "قنبلة يدوية F1 دفاعية روسي",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 2,
    name: "قنبلة يدوية RGD 5 هجومية روسي",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 3,
    name: "قنبلة حسام معدل",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 4,
    name: "قنبلة 40 مم ش ف فردي",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 5,
    name: "قنبلة 40 مم ح ج فردي",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 6,
    name: "قنبلة 40 مم كولت",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 7,
    name: "قنبلة TP تدريب",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 8,
    name: "مفجر للقنابل اليدوية",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 9,
    name: "قنبلة تمثيل جو المعركة 115 M",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 10,
    name: "قنبلة تمثيل جو المعركة 116 M",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 11,
    name: "خرطوشة صيد 12/65",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 12,
    name: "طلقة 5,6 مم مورس عادة صيني",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 13,
    name: "خرطوشة إشارة 26,5 مم أبيض",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 14,
    name: "خرطوشة إشارة 26,5 مم أخضر",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 15,
    name: "خرطوشة إشارة 26,5 مم أحمر",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 16,
    name: "خرطوشة إشارة 26,5 مم مضئ بالبراشوت",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 17,
    name: "خرطوشة إشارة 30 مم أبيض",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 18,
    name: "خرطوشة إشارة 30 مم أحمر",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 19,
    name: "خرطوشة إشارة 30 مم أخضر",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 20,
    name: "طلقة 9 مم عادة",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 21,
    name: "طلقة 7,62×39 مم عادة",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 22,
    name: "طلقة 7,62×39 مم كاشف",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 23,
    name: "طلقة 7,62×51 مم بشرائط",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 24,
    name: "طلقة 7,62×51 مم ناتو ماتش",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 25,
    name: "طلقة 7,62×54 مم ث ح",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 26,
    name: "طلقة 12,7×99 مم M15",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 27,
    name: "مقذوف 40 مم BG7 حارق",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 28,
    name: "مقذوف 40 مم BG7 كوبرا",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 29,
    name: "مقذوف 40 مم BG7 ح ج",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 30,
    name: "مقذوف 40 مم BG7 تدريب",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 31,
    name: "مقذوف M65 ع م",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 32,
    name: "طلقة 12,7×99 مم M9 فشينك",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 33,
    name: "طلقة 5,56×45 مم كاشف أمريكي",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 34,
    name: "طلقة 5,56×45 مم عادة أمريكي",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 35,
    name: "مقلد صوت للصاروخ التو",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 36,
    name: "محدث صوت عبوة عادية",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 37,
    name: "مولد دخان سيمافير بنفسجي",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 38,
    name: "مولد دخان سيمافير أصفر",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 39,
    name: "مولد دخان سيمافير أحمر",
    nationality: "",
    type: "",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الأولي",
  },
  {
    id: 40,
    name: "طلقة 12,7 مم",
    nationality: "روسي",
    type: "ث ح",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 41,
    name: "طلقة 12,7 مم",
    nationality: "صيني",
    type: "ث ح",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 42,
    name: "طلقة 12,7 مم",
    nationality: "مصري",
    type: "ث ح",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 43,
    name: "طلقة 12,7 مم",
    nationality: "روسي",
    type: "ث ح ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 44,
    name: "طلقة 12,7 مم",
    nationality: "مصري",
    type: "ث ح ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 45,
    name: "طلقة 14,5 مم",
    nationality: "مصري",
    type: "ث ح",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 46,
    name: "طلقة 14,5 مم",
    nationality: "روسي",
    type: "ث ح",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 47,
    name: "طلقة 14,5 مم",
    nationality: "روسي",
    type: "ث ح ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 48,
    name: "طلقة 14,5 مم",
    nationality: "مصري",
    type: "ث ح ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 49,
    name: "طلقة 23 مم",
    nationality: "مصري",
    type: "ش ف ح ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 50,
    name: "طلقة 23 مم",
    nationality: "مصري",
    type: "ث ح ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 51,
    name: "طلقة 23 مم",
    nationality: "روسي",
    type: "ش ف ح ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 52,
    name: "طلقة 23 مم",
    nationality: "روسي",
    type: "ش ف ح",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 53,
    name: "طلقة 23 مم",
    nationality: "روسي",
    type: "ث ح ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 54,
    name: "طلقة 23 مم",
    nationality: "روسي",
    type: "بادئ كهربي",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 55,
    name: "بمب هاون 82 مم مطور كامل",
    nationality: "يوغسلافي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 56,
    name: "بمب هاون 82 مم بالسدادة والعبوات",
    nationality: "روسي",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 57,
    name: "بمب هاون 82 مم بالسدادة",
    nationality: "روسي",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 58,
    name: "بمب هاون 82 مم بالسدادة والمكبر",
    nationality: "روسي",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 59,
    name: "بمب هاون 120 مم بالسدادة والعبوات",
    nationality: "روماني",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 60,
    name: "بمب هاون 120 مم كامل",
    nationality: "روسي",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 61,
    name: "بمب هاون 120 مم بالسدادة",
    nationality: "روسي",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 62,
    name: "بمب هاون 120 مم بالسدادة والعبوات",
    nationality: "روسي",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 63,
    name: "بمب هاون 120 مم بالسدادة",
    nationality: "أسباني",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 64,
    name: "بمب هاون 120 مم بالسدادة بدون عبوات",
    nationality: "مصري",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 65,
    name: "بمب هاون 120 مم بالسدادة والعبوات",
    nationality: "مصري",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 66,
    name: "بمب هاون 120 مم بالسدادة والعبوات",
    nationality: "روسي",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 67,
    name: "بمب هاون 120 مم كامل",
    nationality: "روسي",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 68,
    name: "بمب هاون 120 مم كامل",
    nationality: "يوغسلافي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 69,
    name: "بمب هاون 120 مم بالسدادة والعبوات",
    nationality: "يوغسلافي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 70,
    name: "بمب هاون 120 مم كامل",
    nationality: "روسي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 71,
    name: "بمب هاون 120 مم بالسدادة بدون عبوات",
    nationality: "روسي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 72,
    name: "بمب هاون 120 مم بالسدادة والعبوات",
    nationality: "روسي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 73,
    name: "بمب هاون 120 مم بالسدادة بدون عبوات",
    nationality: "مصري",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 74,
    name: "بمب هاون 120 مم بالسدادة والعبوات",
    nationality: "مصري",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 75,
    name: "صاروخ 122 مم بالطابة",
    nationality: "تشيكي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 76,
    name: "صاروخ 122 مم بالسدادة",
    nationality: "تشيكي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 77,
    name: "صاروخ 122 مم بالسدادة",
    nationality: "مصري",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 78,
    name: "صاروخ 122 مم بالسدادة",
    nationality: "روسي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 79,
    name: "صاروخ 122 مم بالسدادة",
    nationality: "كوري",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 80,
    name: "طلقة 122 مم د 30 بالسدادة",
    nationality: "مصري",
    type: "ح ج",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 81,
    name: "طلقة 122 مم د 30 بالطابة",
    nationality: "روسي",
    type: "ح ج",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 82,
    name: "طلقة 122 مم د 30 بالطابة",
    nationality: "باكستاني",
    type: "ش ف ع م",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 83,
    name: "طلقة 122 مم د 30 بالسدادة",
    nationality: "مصري",
    type: "ش ف ع م",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 84,
    name: "طلقة 122 مم د 30 بالسدادة",
    nationality: "مصري",
    type: "ش ف ع ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 85,
    name: "طلقة 122 مم د 30 بالسدادة",
    nationality: "مصري",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 86,
    name: "دانة 122 مم",
    nationality: "يوغسلافي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 87,
    name: "طلقة 130/46 مم بالسدادة",
    nationality: "بمواصفات",
    type: "ش ف ع ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 88,
    name: "طلقة 130/46 مم بالسدادة",
    nationality: "مصري",
    type: "ش ف ع ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 89,
    name: "طلقة 130/46 مم بالسدادة",
    nationality: "كوري",
    type: "ش ف ع ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 90,
    name: "طلقة 130/46 مم بالطابة",
    nationality: "كوري",
    type: "ش ف ع ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 91,
    name: "دانة 155 مم M107",
    nationality: "أمريكي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 92,
    name: "دانة 155 مم مزدوج التأثير",
    nationality: "أمريكي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 93,
    name: "دانة 155 مم دفع صاروخي",
    nationality: "أمريكي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 94,
    name: "دانة 155 مم M107",
    nationality: "باكستاني",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 95,
    name: "دانة 155 مم D550",
    nationality: "أمريكي",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 96,
    name: "دانة 155 مم M110",
    nationality: "فرنساوي",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثانية",
  },
  {
    id: 97,
    name: "صاروخ 122 مم بالطابة",
    nationality: "تشيكي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 98,
    name: "صاروخ 122 مم بالسدادة",
    nationality: "تشيكي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 99,
    name: "صاروخ 122 مم بالسدادة والحلقات",
    nationality: "مصري",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 100,
    name: "صاروخ 122 مم بالسدادة",
    nationality: "روسي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 101,
    name: "صاروخ 122 مم بالسدادة",
    nationality: "كوري",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 102,
    name: "صاروخ تو B1 تدريب",
    nationality: "أمريكي",
    type: "تدريب",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 103,
    name: "صاروخ تو B4 عمليات",
    nationality: "أمريكي",
    type: "عمليات",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 104,
    name: "صاروخ مالوتيكا تاندم مطور",
    nationality: "أمريكي",
    type: "ح ج",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 105,
    name: "صاروخ صقر 10",
    nationality: "مصري",
    type: "تدريب",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 106,
    name: "صاروخ فلاج",
    nationality: "مصري",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 107,
    name: "بمب هاون 120 مم بالسدادة",
    nationality: "مصري",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 108,
    name: "بمب هاون 120 مم كامل",
    nationality: "روسي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 109,
    name: "بمب هاون 120 مم بالسدادة",
    nationality: "مصري",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 110,
    name: "بمب هاون 120 مم بالسدادة والعبوات",
    nationality: "يوغسلافي",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 111,
    name: "بمب هاون 120 مم كامل",
    nationality: "روسي",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 112,
    name: "بمب هاون 120 مم كامل",
    nationality: "روسي",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 113,
    name: "بمب هاون 82 مم بالسدادة",
    nationality: "روسي",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 114,
    name: "طلقة 105 مم بالطابة",
    nationality: "باكستاني",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 115,
    name: "طلقة 105 مم بالسدادة",
    nationality: "مصري",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 116,
    name: "طلقة 105 مم تدريب",
    nationality: "مصري",
    type: "سابو",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 117,
    name: "طلقة 105 مم",
    nationality: "أمريكي",
    type: "ح ج",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 118,
    name: "طلقة 105 مم تدريب",
    nationality: "إيطالي",
    type: "ح ج",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 119,
    name: "طلقة 105 مم تدريب",
    nationality: "مصري",
    type: "ح ج",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 120,
    name: "طلقة 115 مم بالسدادة",
    nationality: "بلغاري",
    type: "ش ف",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 121,
    name: "طلقة 115 مم بالمغلف",
    nationality: "روسي",
    type: "سابو",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 122,
    name: "طلقة 115 مم بالطابة",
    nationality: "روسي",
    type: "ح ج",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 123,
    name: "طلقة 115 مم بالسدادة",
    nationality: "روسي",
    type: "ح ج",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 124,
    name: "طلقة 120 مم تدريب",
    nationality: "مصري",
    type: "سابو",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 125,
    name: "طلقة 120 مم تدريب",
    nationality: "مصري",
    type: "ح ج",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 126,
    name: "طلقة 122 مم د 30 بالسدادة",
    nationality: "مصري",
    type: "ش ف ع م",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 127,
    name: "طلقة 122 مم د 30 بالسدادة",
    nationality: "يوغسلافي",
    type: "ش ف ع ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 128,
    name: "طلقة 122 مم د 30 بالسدادة",
    nationality: "مصري",
    type: "ش ف ع ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 129,
    name: "طلقة 122 مم د 30 بالسدادة",
    nationality: "روسي",
    type: "ش ف ع ك",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 130,
    name: "طلقة 122 مم د 30 بالسدادة",
    nationality: "مصري",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 131,
    name: "طلقة 122 مم د 30 بالسدادة",
    nationality: "مصري",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 132,
    name: "طلقة 130/46 مم بالسدادة",
    nationality: "يوغسلافي",
    type: "ش ف ع م",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 133,
    name: "طلقة 130/46 مم بالطابة",
    nationality: "يوغسلافي",
    type: "ش ف ع م",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 134,
    name: "طلقة 130/46 مم بالسدادة",
    nationality: "بمواصفات",
    type: "ش ف ع م",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 135,
    name: "طلقة 130/46 مم بالسدادة",
    nationality: "مصري",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 135,
    name: "طلقة 130/46 مم بالطابة",
    nationality: "صيني",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 136,
    name: "طلقة 130/46 مم",
    nationality: "روسي",
    type: "ث م",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 137,
    name: "دانة 155 مم بالسدادة",
    nationality: "أمريكي",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 138,
    name: "دانة 155 مم بالسدادة",
    nationality: "فرنساوي",
    type: "مضئ",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
  {
    id: 139,
    name: "دانة 155 مم بالسدادة",
    nationality: "أمريكي",
    type: "دخان",
    hyper: "",
    loot: "",
    box: "",
    number: "",
    boxTwo: "",
    numberTwo: "",
    total: "",
    totalTwo: "",
    group: "المجموعه الثالثة",
  },
];

localStorage.setItem("products", JSON.stringify(products));
